INSERT INTO Players VALUES
(null, 'Alec', null, 0),
(null, 'Ramesh', null, 0),
(null, 'Vijet', null, 0),
(null, 'Reddy', null, 0),
(null, 'Alex', null, 0),
(null, 'Andy', null, 0),
(null, 'Tyler O', null, 0),
(null, 'Bala', null, 0),
(null, 'Megan', null, 0),
(null, 'Venkatesh', null, 0),
(null, 'Tyler L', null, 0),
(null, 'Mohan', null, 0),
(null, 'Faraan', null, 0),
(null, 'Prashamsa', null, 0),
(null, 'Vipul', null, 0),
(null, 'Brendon', null, 0),
(null, 'Chris', null, 0),
(null, 'Vinod', null, 0),
(null, 'Nate', null, 0),
(null, 'Viswa', null, 0),
(null, 'Ellery', null, 0),
(null, 'Eric', null, 0),
(null, 'Mallesh', null, 0),
(null, 'Neel', null, 0);
INSERT INTO Doubles_Tournaments VALUES (NULL, 'Wildlings Hunger Relief Carrom Tournament July 2019', false, null, null, 12, 1, 2, 'Single', 0, 1);
INSERT INTO Teams VALUES
(null, 1, 1, 10),
(null, 1, 2, 3),
(null, 1, 4, 5),
(null, 1, 6, 7),
(null, 1, 8, 9),
(null, 1, 11, 12),
(null, 1, 13, 14),
(null, 1, 15, 16),
(null, 1, 17, 18),
(null, 1, 19, 20),
(null, 1, 21, 22),
(null, 1, 23, 24);
INSERT INTO Doubles_Rounds VALUES (null, 12, 1, 1);
INSERT INTO Doubles_Pools VALUES (null, 1, 1);
INSERT INTO Doubles_Pool_Placements VALUES
(null, 1, 1),
(null, 1, 2),
(null, 1, 3),
(null, 1, 4),
(null, 1, 5),
(null, 1, 6),
(null, 1, 7),
(null, 1, 8),
(null, 1, 9),
(null, 1, 10),
(null, 1, 11),
(null, 1, 12);
INSERT INTO Doubles_Games VALUES
(null, 1, 1, 1, false, null, 1, 2, null, null, null, null, null),
(null, 1, 1, 1, false, null, 1, 3, null, null, null, null, null),
(null, 1, 1, 1, false, null, 1, 4, null, null, null, null, null),
(null, 1, 1, 1, false, null, 1, 5, null, null, null, null, null),
(null, 1, 1, 1, false, null, 1, 6, null, null, null, null, null),
(null, 1, 1, 1, false, null, 1, 7, null, null, null, null, null),
(null, 1, 1, 1, false, null, 1, 8, null, null, null, null, null),
(null, 1, 1, 1, false, null, 1, 9, null, null, null, null, null),
(null, 1, 1, 1, false, null, 1, 10, null, null, null, null, null),
(null, 1, 1, 1, false, null, 1, 11, null, null, null, null, null),
(null, 1, 1, 1, false, null, 1, 12, null, null, null, null, null),
(null, 1, 1, 1, false, null, 2, 3, null, null, null, null, null),
(null, 1, 1, 1, false, null, 2, 4, null, null, null, null, null),
(null, 1, 1, 1, false, null, 2, 5, null, null, null, null, null),
(null, 1, 1, 1, false, null, 2, 6, null, null, null, null, null),
(null, 1, 1, 1, false, null, 2, 7, null, null, null, null, null),
(null, 1, 1, 1, false, null, 2, 8, null, null, null, null, null),
(null, 1, 1, 1, false, null, 2, 9, null, null, null, null, null),
(null, 1, 1, 1, false, null, 2, 10, null, null, null, null, null),
(null, 1, 1, 1, false, null, 2, 11, null, null, null, null, null),
(null, 1, 1, 1, false, null, 2, 12, null, null, null, null, null),
(null, 1, 1, 1, false, null, 3, 4, null, null, null, null, null),
(null, 1, 1, 1, false, null, 3, 5, null, null, null, null, null),
(null, 1, 1, 1, false, null, 3, 6, null, null, null, null, null),
(null, 1, 1, 1, false, null, 3, 7, null, null, null, null, null),
(null, 1, 1, 1, false, null, 3, 8, null, null, null, null, null),
(null, 1, 1, 1, false, null, 3, 9, null, null, null, null, null),
(null, 1, 1, 1, false, null, 3, 10, null, null, null, null, null),
(null, 1, 1, 1, false, null, 3, 11, null, null, null, null, null),
(null, 1, 1, 1, false, null, 3, 12, null, null, null, null, null),
(null, 1, 1, 1, false, null, 4, 5, null, null, null, null, null),
(null, 1, 1, 1, false, null, 4, 6, null, null, null, null, null),
(null, 1, 1, 1, false, null, 4, 7, null, null, null, null, null),
(null, 1, 1, 1, false, null, 4, 8, null, null, null, null, null),
(null, 1, 1, 1, false, null, 4, 9, null, null, null, null, null),
(null, 1, 1, 1, false, null, 4, 10, null, null, null, null, null),
(null, 1, 1, 1, false, null, 4, 11, null, null, null, null, null),
(null, 1, 1, 1, false, null, 4, 12, null, null, null, null, null),
(null, 1, 1, 1, false, null, 5, 6, null, null, null, null, null),
(null, 1, 1, 1, false, null, 5, 7, null, null, null, null, null),
(null, 1, 1, 1, false, null, 5, 8, null, null, null, null, null),
(null, 1, 1, 1, false, null, 5, 9, null, null, null, null, null),
(null, 1, 1, 1, false, null, 5, 10, null, null, null, null, null),
(null, 1, 1, 1, false, null, 5, 11, null, null, null, null, null),
(null, 1, 1, 1, false, null, 5, 12, null, null, null, null, null),
(null, 1, 1, 1, false, null, 6, 7, null, null, null, null, null),
(null, 1, 1, 1, false, null, 6, 8, null, null, null, null, null),
(null, 1, 1, 1, false, null, 6, 9, null, null, null, null, null),
(null, 1, 1, 1, false, null, 6, 10, null, null, null, null, null),
(null, 1, 1, 1, false, null, 6, 11, null, null, null, null, null),
(null, 1, 1, 1, false, null, 6, 12, null, null, null, null, null),
(null, 1, 1, 1, false, null, 7, 8, null, null, null, null, null),
(null, 1, 1, 1, false, null, 7, 9, null, null, null, null, null),
(null, 1, 1, 1, false, null, 7, 10, null, null, null, null, null),
(null, 1, 1, 1, false, null, 7, 11, null, null, null, null, null),
(null, 1, 1, 1, false, null, 7, 12, null, null, null, null, null),
(null, 1, 1, 1, false, null, 8, 9, null, null, null, null, null),
(null, 1, 1, 1, false, null, 8, 10, null, null, null, null, null),
(null, 1, 1, 1, false, null, 8, 11, null, null, null, null, null),
(null, 1, 1, 1, false, null, 8, 12, null, null, null, null, null),
(null, 1, 1, 1, false, null, 9, 10, null, null, null, null, null),
(null, 1, 1, 1, false, null, 9, 11, null, null, null, null, null),
(null, 1, 1, 1, false, null, 9, 12, null, null, null, null, null),
(null, 1, 1, 1, false, null, 10, 11, null, null, null, null, null),
(null, 1, 1, 1, false, null, 10, 12, null, null, null, null, null),
(null, 1, 1, 1, false, null, 11, 12, null, null, null, null, null);