INSERT INTO Singles_Tournaments VALUES (NULL, 'Hunger Relief January 2019', false, null, null, 24, 1, 2, 'Single', 0, 1);
INSERT INTO Singles_Rounds VALUES (null, 24, 1, 2);
INSERT INTO Singles_Pools VALUES (null, 1, 1), (null, 1, 1), (null, 1, 1), (null, 1, 1);
INSERT INTO Singles_Pool_Placements VALUES
(null, 1, 5), (null, 1, 25), (null, 1, 6), (null, 1, 20), (null, 1, 26), (null, 1, 17),
(null, 2, 10), (null, 2, 16),(null, 2, 3),(null, 2, 18),(null, 2, 2),(null, 2, 15),
(null, 3, 21),(null, 3, 11),(null, 3, 4),(null, 3, 27),(null, 3, 19),(null, 3, 1),
(null, 4, 23),(null, 4, 29),(null, 4, 30),(null, 4, 13),(null, 4, 8),(null, 4, 28);
INSERT INTO Singles_Games VALUES
(null, 1, 1, 1, false, null, 5, 25, null, null, null, null, null),
(null, 1, 1, 1, false, null, 5, 6, null, null, null, null, null),
(null, 1, 1, 1, false, null, 5, 20, null, null, null, null, null),
(null, 1, 1, 1, false, null, 5, 26, null, null, null, null, null),
(null, 1, 1, 1, false, null, 5, 17, null, null, null, null, null),
(null, 1, 1, 1, false, null, 6, 25, null, null, null, null, null),
(null, 1, 1, 1, false, null, 6, 20, null, null, null, null, null),
(null, 1, 1, 1, false, null, 6, 26, null, null, null, null, null),
(null, 1, 1, 1, false, null, 6, 17, null, null, null, null, null),
(null, 1, 1, 1, false, null, 20, 25, null, null, null, null, null),
(null, 1, 1, 1, false, null, 20, 26, null, null, null, null, null),
(null, 1, 1, 1, false, null, 20, 17, null, null, null, null, null),
(null, 1, 1, 1, false, null, 26, 17, null, null, null, null, null),
(null, 1, 1, 1, false, null, 26, 25, null, null, null, null, null),
(null, 1, 1, 1, false, null, 17, 25, null, null, null, null, null),
(null, 1, 1, 2, false, null, 10, 16, null, null, null, null, null),
(null, 1, 1, 2, false, null, 10, 3, null, null, null, null, null),
(null, 1, 1, 2, false, null, 10, 18, null, null, null, null, null),
(null, 1, 1, 2, false, null, 10, 2, null, null, null, null, null),
(null, 1, 1, 2, false, null, 10, 15, null, null, null, null, null),
(null, 1, 1, 2, false, null, 16, 3, null, null, null, null, null),
(null, 1, 1, 2, false, null, 16, 18, null, null, null, null, null),
(null, 1, 1, 2, false, null, 16, 2, null, null, null, null, null),
(null, 1, 1, 2, false, null, 16, 15, null, null, null, null, null),
(null, 1, 1, 2, false, null, 3, 18, null, null, null, null, null),
(null, 1, 1, 2, false, null, 3, 2, null, null, null, null, null),
(null, 1, 1, 2, false, null, 3, 15, null, null, null, null, null),
(null, 1, 1, 2, false, null, 18, 2, null, null, null, null, null),
(null, 1, 1, 2, false, null, 18, 15, null, null, null, null, null),
(null, 1, 1, 2, false, null, 2, 15, null, null, null, null, null),
(null, 1, 1, 3, false, null, 21, 11, null, null, null, null, null),
(null, 1, 1, 3, false, null, 21, 4, null, null, null, null, null),
(null, 1, 1, 3, false, null, 21, 27, null, null, null, null, null),
(null, 1, 1, 3, false, null, 21, 19, null, null, null, null, null),
(null, 1, 1, 3, false, null, 21, 1, null, null, null, null, null),
(null, 1, 1, 3, false, null, 11, 4, null, null, null, null, null),
(null, 1, 1, 3, false, null, 11, 27, null, null, null, null, null),
(null, 1, 1, 3, false, null, 11, 19, null, null, null, null, null),
(null, 1, 1, 3, false, null, 11, 1, null, null, null, null, null),
(null, 1, 1, 3, false, null, 4, 27, null, null, null, null, null),
(null, 1, 1, 3, false, null, 4, 19, null, null, null, null, null),
(null, 1, 1, 3, false, null, 4, 1, null, null, null, null, null),
(null, 1, 1, 3, false, null, 27, 19, null, null, null, null, null),
(null, 1, 1, 3, false, null, 27, 1, null, null, null, null, null),
(null, 1, 1, 3, false, null, 1, 19, null, null, null, null, null),
(null, 1, 1, 4, false, null, 23, 29, null, null, null, null, null),
(null, 1, 1, 4, false, null, 23, 30, null, null, null, null, null),
(null, 1, 1, 4, false, null, 23, 13, null, null, null, null, null),
(null, 1, 1, 4, false, null, 23, 8, null, null, null, null, null),
(null, 1, 1, 4, false, null, 23, 28, null, null, null, null, null),
(null, 1, 1, 4, false, null, 29, 30, null, null, null, null, null),
(null, 1, 1, 4, false, null, 29, 13, null, null, null, null, null),
(null, 1, 1, 4, false, null, 29, 8, null, null, null, null, null),
(null, 1, 1, 4, false, null, 29, 28, null, null, null, null, null),
(null, 1, 1, 4, false, null, 30, 13, null, null, null, null, null),
(null, 1, 1, 4, false, null, 30, 8, null, null, null, null, null),
(null, 1, 1, 4, false, null, 30, 28, null, null, null, null, null),
(null, 1, 1, 4, false, null, 13, 8, null, null, null, null, null),
(null, 1, 1, 4, false, null, 13, 28, null, null, null, null, null),
(null, 1, 1, 4, false, null, 28, 8, null, null, null, null, null);